sources:
  - ./FataExample/Services/
templates:
  - ./../Template/
output: 
  ./FataExampleTests/mocks/
args:
  testableModule: "FataExample"
  imports: "import CoreLocation\nimport CoreData"
  returnEmptyArray: false
  returnEmptyDict: false